/*
-- Query: SELECT * FROM web_shr_v1.brands
LIMIT 0, 1000

-- Date: 2022-09-07 13:49
*/
INSERT INTO `` (`ID`,`NAME`) VALUES (1,'BURBERRY');
INSERT INTO `` (`ID`,`NAME`) VALUES (2,'BIG FISH');
INSERT INTO `` (`ID`,`NAME`) VALUES (3,'BLACK EYES');
INSERT INTO `` (`ID`,`NAME`) VALUES (4,'WHIRLWIND');
INSERT INTO `` (`ID`,`NAME`) VALUES (5,'HAPPY MOMY');
INSERT INTO `` (`ID`,`NAME`) VALUES (6,'Sound of Silent');
