/*
-- Query: SELECT * FROM web_shr_v1.user_roles
LIMIT 0, 1000

-- Date: 2022-09-08 09:44
*/
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (1,1,1);
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (2,2,1);
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (3,2,2);
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (4,3,2);
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (5,4,2);
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (6,5,2);
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (7,6,2);
INSERT INTO `` (`ID`,`USER_ID`,`ROLE_ID`) VALUES (8,7,2);
