/*
-- Query: SELECT * FROM web_shr_v1.sold_products
LIMIT 0, 1000

-- Date: 2022-09-07 13:23
*/
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (1,50,3,6);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (2,12,1,3);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (3,40,2,6);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (4,56,2,4);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (5,5,2,4);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (6,36,2,4);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (7,14,7,27);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (8,22,8,20);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (9,26,10,15);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (10,15,2,2);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (11,11,1,1);
INSERT INTO `` (`ID`,`PRODUCT_ID`,`SALE_NUMBER`,`SELL_NUMBER`) VALUES (12,25,1,1);
