/*
-- Query: SELECT * FROM web_shr_v1.users
LIMIT 0, 1000

-- Date: 2022-09-06 15:42
*/
INSERT INTO `` (`ID`,`USER_NAME`,`PHONE`,`EMAIL`,`SHIPPING_ADDRESS`,`USER_PASS`,`ENABLED`,`AUTH_PROVIDER`,`OTP`,`OTP_CREATE_TIME`,`LOCKED`) VALUES (1,'ADMIN 1','0356657701','A1@GMAIL.COM','SHIPPING ADDRESS 1','$2a$10$L.5NHjkHk7jTvFBx5i4mrOuAF/2TfV518KmS2nTuzYDn3ZQ3C0WtG\r\n',1,'LOCAL',NULL,NULL,0);
INSERT INTO `` (`ID`,`USER_NAME`,`PHONE`,`EMAIL`,`SHIPPING_ADDRESS`,`USER_PASS`,`ENABLED`,`AUTH_PROVIDER`,`OTP`,`OTP_CREATE_TIME`,`LOCKED`) VALUES (2,'ADMIN 2','0356657722','A2@GMAIL.COM','KTX Khu B ĐẠI HỌC QUỐC GIA TP.HCM 2s','$2a$10$zz4LIAxbPMVB2qdpyynQjexC7Ktvky89Ge/oX5LYcBmGF0978y7Qq',1,'LOCAL',NULL,NULL,0);
INSERT INTO `` (`ID`,`USER_NAME`,`PHONE`,`EMAIL`,`SHIPPING_ADDRESS`,`USER_PASS`,`ENABLED`,`AUTH_PROVIDER`,`OTP`,`OTP_CREATE_TIME`,`LOCKED`) VALUES (3,'CUSTOMER 1','0356657703','C1@GMAIL.COM','SHIPPING ADDRESS 1','$2a$10$DVPZrjKyLanizwcamYGyX.rsF.VseCqhCR3ElqPkwkVcoXysUS.CO',1,'LOCAL',NULL,NULL,0);
INSERT INTO `` (`ID`,`USER_NAME`,`PHONE`,`EMAIL`,`SHIPPING_ADDRESS`,`USER_PASS`,`ENABLED`,`AUTH_PROVIDER`,`OTP`,`OTP_CREATE_TIME`,`LOCKED`) VALUES (4,'CUSTOMER 2','0356657704','C2@GMAIL.COM','SHIPPING ADDRESS 2','$2a$10$ms30lQ1xErvVxhnL7Ri3Mu/W1drVeOeqQFitFJCMpMmedD9PyaQe2',1,'LOCAL',NULL,NULL,0);
INSERT INTO `` (`ID`,`USER_NAME`,`PHONE`,`EMAIL`,`SHIPPING_ADDRESS`,`USER_PASS`,`ENABLED`,`AUTH_PROVIDER`,`OTP`,`OTP_CREATE_TIME`,`LOCKED`) VALUES (5,'CUSTOMER 3','0356657705','C3@GMAIL.COM','SHIPPING ADDRESS 3','$2a$10$RTDB9yfu/AosHaQuQwWDF.qWcXX1FxzQxeeWrthYH/lJpsXLElrpO',1,'LOCAL',NULL,NULL,0);
INSERT INTO `` (`ID`,`USER_NAME`,`PHONE`,`EMAIL`,`SHIPPING_ADDRESS`,`USER_PASS`,`ENABLED`,`AUTH_PROVIDER`,`OTP`,`OTP_CREATE_TIME`,`LOCKED`) VALUES (6,'CUSTOMER 4','0356657706','C4@GMAIL.COM','SHIPPING ADDRESS 4','$2a$10$.1UcqkWKlCyKAqKu47uPB.WsfVkjElrehOm6r4iu3pa79/Z0LXeVC\r\n',1,'LOCAL',NULL,NULL,0);
INSERT INTO `` (`ID`,`USER_NAME`,`PHONE`,`EMAIL`,`SHIPPING_ADDRESS`,`USER_PASS`,`ENABLED`,`AUTH_PROVIDER`,`OTP`,`OTP_CREATE_TIME`,`LOCKED`) VALUES (7,'Old Man Silver',NULL,'thanhtinh14.06.1998@gmail.com',NULL,'$2a$10$5J6VBWd.jUcdx9HL/ojgbeYnK7fK8ZNDgotc4XIELm7q4biyElYIy',1,'GOOGLE',NULL,NULL,0);
