-- PgSQL --
CREATE TABLE USERS (
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
USER_NAME VARCHAR(100),
PHONE VARCHAR(100),
EMAIL VARCHAR(100),
SHIPPING_ADDRESS VARCHAR(200),
USER_PASS VARCHAR(200),
ENABLED BOOLEAN,
AUTH_PROVIDER VARCHAR(15),
OTP VARCHAR(200),
OTP_CREATE_TIME DATE,
LOCKED BOOLEAN
)

CREATE TABLE USER_ROLES(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
USER_ID INT REFERENCES USERS(ID),
ROLE_ID INT NOT NULL
)
create table persistent_logins (
	username varchar(64) not null,
	series varchar(64) primary key,
	token varchar(64) not null,
	last_used timestamp not null
)
CREATE TABLE PRODUCTS (
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
NAME TEXT,
IMAGES_PATH VARCHAR(100),
PRICE INT,
DESCRIPTION TEXT,
BRAND_ID INT REFERENCES BRANDS(ID) ,
CATEGORY_ID INT REFERENCES CATEGORIES(ID),
QUANTITY INT,
FIRST_IMAGE VARCHAR(200)  NULL ,
CREATE_AT DATE,
RATING INT
)
CREATE TABLE CART_ITEMS (
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
USER_ID INT REFERENCES USERS(ID) ,
PRODUCT_ID INT REFERENCES PRODUCTS(ID), 
QUANTITY INT
)

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
USER_ID INT REFERENCES USERS(ID) NOT NULL,
RECIPIENT VARCHAR(200),
EMAIL VARCHAR(200),
PHONE VARCHAR(200),
SHIPPING_ADDRESS VARCHAR(200),
NOTE VARCHAR(200),
GRAND_TOTAL BIGINT NOT NULL,
SHIPPING_METHOD_ID INT REFERENCES SHIPPING_METHODS(ID) NOT NULL,
PAYMENT_METHOD_ID INT REFERENCES PAYMENT_METHODS(ID) NOT NULL,
EARLIEST_DELIVERY_TIME DATE ,
LATEST_DELIVERY_TIME DATE ,
SUCCESSFUL_DELIVERY_TIME DATE,
STATUS VARCHAR(100) NOT NULL,
CREATE_AT DATE,
UPDATE_AT DATE

)
CREATE TABLE REVIEWS (
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
USER_ID INT REFERENCES USERS(ID),
PRODUCT_ID INT REFERENCES PRODUCTS(ID), 
REVIEW TEXT,
CREATE_TIME DATE,
RATING INT,
IMAGE TEXT,
BUY_TIME DATE
)
CREATE TABLE OTP (
EMAIL VARCHAR(100) ,
CODE VARCHAR(100)
)
CREATE TABLE SHIPPING_METHODS(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
NAME VARCHAR(100) NOT NULL,
DESCRIPTION TEXT NOT NULL,
SHIPPING_COST INT NOT NULL,
EARLIEST_DELIVERY_DAY INT NOT NULL,
LATEST_DELIVERY_DAY INT NOT NULL,
IMAGE TEXT 
	)

CREATE TABLE PAYMENT_METHODS(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
NAME VARCHAR(100) NOT NULL,
DESCRIPTION TEXT NOT NULL,
IMAGE TEXT
)
CREATE TABLE ORDER_ITEMS (
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
PRODUCT_ID INT REFERENCES PRODUCTS(ID) NOT NULL,
QUANTITY INT NOT NULL,
ORDER_ID INT REFERENCES ORDERS(ORDER_ID) NOT NULL
	)
    	CREATE TABLE SOLD_PRODUCTS (
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
PRODUCT_ID INT REFERENCES PRODUCTS(ID) NOT NULL,
SALE_NUMBER INT ,
SELL_NUMBER INT
)
CREATE TABLE BRANDS(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
NAME VARCHAR(100) NOT NULL
)

-- CATEGORIES
CREATE TABLE CATEGORIES(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
NAME VARCHAR(100) NOT NULL,
CLASS_ICON VARCHAR(200) NOT NULL
)

-- specifications
CREATE TABLE SPECIFICATIONS(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
PRODUCT_ID INT REFERENCES PRODUCTS(ID) NOT NULL,
ORDINAL INT NOT NULL,
PARAMETER VARCHAR(100) NOT NULL,
DETAIL VARCHAR (200) NOT NULL
)

-- descriptions
CREATE TABLE DESCRIPTIONS(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL,
PRODUCT_ID INT REFERENCES PRODUCTS(ID) NOT NULL,
DESCRIPTION TEXT NOT NULL
)