/*
-- Query: SELECT * FROM web_shr_v1.sold_products
LIMIT 0, 1000

-- Date: 2022-09-07 13:23
*/
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (50,3,6);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (12,1,3);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (40,2,6);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (56,2,4);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (5,2,4);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (36,2,4);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (14,7,27);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (22,8,20);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (26,10,15);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (15,2,2);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (11,1,1);
INSERT INTO SOLD_PRODUCTS (PRODUCT_ID,SALE_NUMBER,SELL_NUMBER) VALUES (25,1,1);
