/*
-- Query: SELECT * FROM web_shr_v1.brands
LIMIT 0, 1000

-- Date: 2022-09-07 13:49
*/
INSERT INTO BRANDS  (NAME) VALUES ('BURBERRY');
INSERT INTO BRANDS  (NAME) VALUES ('BIG FISH');
INSERT INTO BRANDS  (NAME) VALUES ('BLACK EYES');
INSERT INTO BRANDS  (NAME) VALUES ('WHIRLWIND');
INSERT INTO BRANDS  (NAME) VALUES ('HAPPY MOMY');
INSERT INTO BRANDS  (NAME) VALUES ('Sound of Silent');
