CREATE OR REPLACE FUNCTION update_rating() RETURNS trigger AS $update_rating$
	DECLARE
	R_SUM INT = (SELECT SUM(RATING) FROM REVIEWS WHERE PRODUCT_ID = NEW.PRODUCT_ID);
	R_COUNT INT = (SELECT COUNT(RATING) FROM REVIEWS WHERE PRODUCT_ID = NEW.PRODUCT_ID);
	BEGIN
	UPDATE PRODUCTS SET RATING =  CEILING (R_SUM/R_COUNT) WHERE ID = NEW.PRODUCT_ID;
	END
$update_rating$ LANGUAGE plpgsql;
CREATE TRIGGER update_rating AFTER INSERT ON REVIEWS
	FOR EACH ROW EXECUTE FUNCTION update_rating() ;


