CREATE TRIGGER TG_INSERT_ORDER_ITEMS AFTER INSERT  ON web_shr_v1.order_items
FOR EACH ROW
BEGIN
SET @oID  =  NEW.;
-- DECLARE INPUT_SELL_NUMBER INT = (SELECT QUANTITY FROM new.);

IF EXISTS (SELECT * FROM SOLD_PRODUCTS WHERE SOLD_PRODUCTS.PRODUCT_ID = NEW_PID) 
THEN 
-- 	BEGIN
-- 	DECLARE CURRENT_SALE_NUMBER INT = (SELECT SALE_NUMBER FROM SOLD_PRODUCTS WHERE PRODUCT_ID = NEW_PID);
-- 	DECLARE CURRENT_SELL_NUMBER INT = (SELECT SELL_NUMBER FROM SOLD_PRODUCTS WHERE PRODUCT_ID = NEW_PID);
-- 	SET CURRENT_SALE_NUMBER = CURRENT_SALE_NUMBER + 1;
-- 	SET CURRENT_SELL_NUMBER = CURRENT_SELL_NUMBER + INPUT_SELL_NUMBER;
-- 	UPDATE SOLD_PRODUCTS SET SALE_NUMBER = CURRENT_SALE_NUMBER, SELL_NUMBER = CURRENT_SELL_NUMBER WHERE PRODUCT_ID = NEW_PID;
-- 	END
END IF;
-- 	ELSE
-- 	BEGIN
-- 	INSERT INTO SOLD_PRODUCTS ( PRODUCT_ID, SALE_NUMBER, SELL_NUMBER ) VALUES( NEW_PID, 1, INPUT_SELL_NUMBER);
-- 	END
    
END

