--l create
USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[BRANDS]    Script Date: 11/07/2021 11:51:12 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BRANDS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[CART_ITEMS]    Script Date: 11/07/2021 11:51:33 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CART_ITEMS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[QUANTITY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CART_ITEMS]  WITH CHECK ADD FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[PRODUCTS] ([ID])
GO

ALTER TABLE [dbo].[CART_ITEMS]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO

USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[CATEGORIES]    Script Date: 11/07/2021 11:52:15 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORIES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[PRODUCTS]    Script Date: 12/07/2021 12:00:32 SA ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](200) NULL,
	[IMAGES_PATH] [nvarchar](100) NULL,
	[PRICE] [int] NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[BRAND_ID] [int] NULL,
	[CATEGORY_ID] [int] NULL,
	[QUANTITY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUCTS]  WITH CHECK ADD FOREIGN KEY([BRAND_ID])
REFERENCES [dbo].[BRANDS] ([ID])
GO

ALTER TABLE [dbo].[PRODUCTS]  WITH CHECK ADD FOREIGN KEY([CATEGORY_ID])
REFERENCES [dbo].[CATEGORIES] ([ID])
GO



USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[DESCRIPTIONS]    Script Date: 11/07/2021 11:52:33 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DESCRIPTIONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT_ID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[DESCRIPTIONS]  WITH CHECK ADD FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[PRODUCTS] ([ID])
GO

USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[ORDER_ITEMS]    Script Date: 11/07/2021 11:52:50 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORDER_ITEMS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT_ID] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[ORDER_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORDER_ITEMS]  WITH CHECK ADD FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ORDERS] ([ORDER_ID])
GO

ALTER TABLE [dbo].[ORDER_ITEMS]  WITH CHECK ADD FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[PRODUCTS] ([ID])
GO


USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[ORDERS]    Script Date: 11/07/2021 11:53:00 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORDERS](
	[ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[RECIPIENT] [nvarchar](200) NULL,
	[EMAIL] [nvarchar](200) NULL,
	[PHONE] [nvarchar](200) NULL,
	[SHIPPING_ADDRESS] [nvarchar](200) NULL,
	[NOTE] [nvarchar](200) NULL,
	[GRAND_TOTAL] [bigint] NOT NULL,
	[SHIPPING_METHOD] [nvarchar](200) NOT NULL,
	[PAYMENT_METHOD] [nvarchar](200) NOT NULL,
	[EARLIEST_DELIVERY_TIME] [date] NULL,
	[LATEST_DELIVERY_TIME] [date] NULL,
	[SUCCESSFUL_DELIVERY_TIME] [date] NULL,
	[STATUS] [nvarchar](100) NOT NULL,
	[CREATE_AT] [date] NULL,
	[UPDATE_AT] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO

USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[OTP]    Script Date: 11/07/2021 11:53:13 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OTP](
	[EMAIL] [nvarchar](100) NULL,
	[CODE] [nvarchar](100) NULL
) ON [PRIMARY]
GO
USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[REVIEWS]    Script Date: 11/07/2021 11:53:33 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REVIEWS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[USER_NAME] [nvarchar](100) NULL,
	[REVIEW] [nvarchar](max) NULL,
	[CREATE_TIME] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [WEB_SHR_V1]
GO

/****** Object:  Table [dbo].[SPECIFICATIONS]    Script Date: 11/07/2021 11:54:06 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SPECIFICATIONS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PRODUCT_ID] [int] NOT NULL,
	[ORDINAL] [int] NOT NULL,
	[PARAMETER] [nvarchar](100) NOT NULL,
	[DETAIL] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SPECIFICATIONS]  WITH CHECK ADD FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[PRODUCTS] ([ID])
GO





