USE WEB_SHR_V1
GO
-- brands
CREATE TABLE BRANDS(
ID INT PRIMARY KEY IDENTITY NOT NULL ,
NAME NVARCHAR(100) NOT NULL
)
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.BRANDS TO [SHR_Main]
-- CATEGORIES
CREATE TABLE CATEGORIES(
ID INT PRIMARY KEY IDENTITY NOT NULL,
NAME NVARCHAR(100) NOT NULL
)
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.CATEGORIES TO [SHR_Main]
-- specifications
CREATE TABLE SPECIFICATIONS(
ID INT PRIMARY KEY IDENTITY NOT NULL,
PRODUCT_ID INT REFERENCES dbo.PRODUCTS(ID) NOT NULL,
ORDINAL INT NOT NULL,
PARAMETER NVARCHAR(100) NOT NULL,
DETAIL NVARCHAR (200) NOT NULL
)
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.SPECIFICATIONS TO [SHR_Main]
-- descriptions
CREATE TABLE DESCRIPTIONS(
ID INT PRIMARY KEY IDENTITY NOT NULL,
PRODUCT_ID INT REFERENCES dbo.PRODUCTS(ID) NOT NULL,
DESCRIPTION NVARCHAR(MAX) NOT NULL
)
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.DESCRIPTIONS TO [SHR_Main]