
/*
Author : Nguyễn Thanh Tính (SHR)
Mssv   : 17130246
Class  : DH17DTA
Project : WEB SHR v1
Time create : 06/12/2020.

*/
-- CREATE DATABASE AND USE IT
CREATE DATABASE WEB_SHR_V1
GO
USE WEB_SHR_V1
GO
/* user for database
Create login SHR_Main with password='SHR_Main'
*/

-- CREATE TABLE USER - PHÂN BIỆT ADMIN VỚI CUSTOMER BẰNG  ROLE
CREATE TABLE USERS (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
USER_NAME NVARCHAR(100),
PHONE NVARCHAR(100),
EMAIL NVARCHAR(100),
SHIPPING_ADDRESS NVARCHAR(200),
USER_PASS NVARCHAR(200),
ENABLED BIT
)
GO
-- INSERT USER ADMIN DATA TO TABLE (DEMO DATA)
INSERT INTO USERS (USER_NAME,PHONE,EMAIL,SHIPPING_ADDRESS,USER_PASS,ENABLED) VALUES ( 'ADMIN 1','0356657701','A1@GMAIL.COM','PAYMENT ADDRESS 1','SHIPPING ADDRESS 1','PASSA1',1);
INSERT INTO USERS (USER_NAME,PHONE,EMAIL,SHIPPING_ADDRESS,USER_PASS,ENABLED) VALUES ( 'ADMIN 2','0356657702','A2@GMAIL.COM','PAYMENT ADDRESS 2','SHIPPING ADDRESS 2','PASSA2',1);

INSERT INTO USERS (USER_NAME,PHONE,EMAIL,SHIPPING_ADDRESS,USER_PASS,ENABLED) VALUES ( 'CUSTOMER 1','0356657703','C1@GMAIL.COM','SHIPPING ADDRESS 1','PASSC1',1);
INSERT INTO USERS (USER_NAME,PHONE,EMAIL,SHIPPING_ADDRESS,USER_PASS,ENABLED) VALUES ( 'CUSTOMER 2','0356657704','C2@GMAIL.COM','SHIPPING ADDRESS 2','PASSC2',1);
INSERT INTO USERS (USER_NAME,PHONE,EMAIL,SHIPPING_ADDRESS,USER_PASS,ENABLED) VALUES ( 'CUSTOMER 3','0356657705','C3@GMAIL.COM','SHIPPING ADDRESS 3','PASSC3',1);
INSERT INTO USERS (USER_NAME,PHONE,EMAIL,SHIPPING_ADDRESS,USER_PASS,ENABLED) VALUES ( 'CUSTOMER 4','0356657706','C4@GMAIL.COM','SHIPPING ADDRESS 4','PASSC4',1);

-- grant access for SHR_Main
GRANT INSERT, SELECT, UPDATE ON dbo.USERS TO [SHR_Main]
CREATE TABLE USER_ROLES(
USER_ID INT  NOT NULL,
ROLE_ID INT NOT NULL,
PRIMARY KEY (USER_ID)
)
GO
GRANT INSERT, SELECT, UPDATE ON dbo.USER_ROLES TO [SHR_Main]
INSERT INTO USER_ROLES VALUES (6,1);
INSERT INTO USER_ROLES VALUES (7,1);
INSERT INTO USER_ROLES VALUES (12,2);
INSERT INTO USER_ROLES VALUES (13,2);



/*
SOME EX
SELECT * FROM CUSTOMER WHERE CUSTOMER.EMAIL = 'kh01@gmail.com' AND CUSTOMER.PASSWORD = 'password1';
UPDATE CUSTOMER SET NAME ='NAME_UPDATE' WHERE EMAIL ='KH01@GMAIL.COM'
UPDATE CUSTOMER SET NAME ='CUSTOMER 1' WHERE EMAIL ='KH01@GMAIL.COM'
*/

-- CREATE TABLE PRODUCT
CREATE TABLE PRODUCTS (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
NAME NVARCHAR(100),
IMAGES_PATH NVARCHAR(100),
PRICE INT,
DESCRIPTION NVARCHAR(MAX),
BRAND NVARCHAR(100),
CATEGORY NVARCHAR(100),
QUANTITY INT
)
GO
-- INSERT DATA TO TABLE (DEMO DATA) 15 PRODUCT
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 1','IMAGES_PATH 1',400000,'DESCRIPTION 1','BRAND 1','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 2','IMAGES_PATH 2',4500000,'DESCRIPTION 2','BRAND 1','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 3','IMAGES_PATH 3',31000,'DESCRIPTION 3','BRAND 4','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 4','IMAGES_PATH 4',250000,'DESCRIPTION 4','BRAND 3','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 5','IMAGES_PATH 5',390000,'DESCRIPTION 5','BRAND 2','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 6','IMAGES_PATH 6',520000,'DESCRIPTION 6','BRAND 4','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 7','IMAGES_PATH 7',199000,'DESCRIPTION 7','BRAND 2','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 8','IMAGES_PATH 8',70000,'DESCRIPTION 8','BRAND 2','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 9','IMAGES_PATH 9',650000,'DESCRIPTION 9','BRAND 2','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 10','IMAGES_PATH 10',100000,'DESCRIPTION 10','BRAND 2','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 11','IMAGES_PATH 11',100000,'DESCRIPTION 11','BRAND 4','MEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 12','IMAGES_PATH 12',100000,'DESCRIPTION 12','BRAND 4','MEN CLOTHES',100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 13','IMAGES_PATH 13',1000000,'DESCRIPTION 13','BRAND 3','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 14','IMAGES_PATH 14',700000,'DESCRIPTION 14','BRAND 4','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 15','IMAGES_PATH 15',70000,'DESCRIPTION 15','BRAND 1','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 16','IMAGES_PATH 16',90000,'DESCRIPTION 16','BRAND 1','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 17','IMAGES_PATH 17',330000,'DESCRIPTION 17','BRAND 1','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 18','IMAGES_PATH 18',550000,'DESCRIPTION 18','BRAND 1','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 19','IMAGES_PATH 19',100000,'DESCRIPTION 19','BRAND 2','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 20','IMAGES_PATH 20',100000,'DESCRIPTION 20','BRAND 1','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 21','IMAGES_PATH 21',100000,'DESCRIPTION 21','BRAND 3','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 22','IMAGES_PATH 22',750000,'DESCRIPTION 22','BRAND 2','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 23','IMAGES_PATH 23',410000,'DESCRIPTION 23','BRAND 1','WOMEN CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 24','IMAGES_PATH 24',155000,'DESCRIPTION 24','BRAND 4','WOMEN CLOTHES',100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 25','IMAGES_PATH 25',200000,'DESCRIPTION 25','BRAND 1','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 26','IMAGES_PATH 26',200000,'DESCRIPTION 26','BRAND 1','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 27','IMAGES_PATH 27',300000,'DESCRIPTION 27','BRAND 2','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 28','IMAGES_PATH 28',100000,'DESCRIPTION 28','BRAND 2','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 29','IMAGES_PATH 29',100000,'DESCRIPTION 29','BRAND 2','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 30','IMAGES_PATH 30',500000,'DESCRIPTION 30','BRAND 3','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 31','IMAGES_PATH 31',600000,'DESCRIPTION 31','BRAND 4','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 32','IMAGES_PATH 32',700000,'DESCRIPTION 32','BRAND 1','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 33','IMAGES_PATH 33',80000,'DESCRIPTION 33','BRAND 3','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 34','IMAGES_PATH 34',420000,'DESCRIPTION 34','BRAND 1','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 35','IMAGES_PATH 35',90000,'DESCRIPTION 35','BRAND 2','KIDS AND BABIES CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 36','IMAGES_PATH 36',150000,'DESCRIPTION 36','BRAND 1','KIDS AND BABIES CLOTHES',100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 37','IMAGES_PATH 37',100000,'DESCRIPTION 37','BRAND 1','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 38','IMAGES_PATH 38',800000,'DESCRIPTION 38','BRAND 4','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 39','IMAGES_PATH 39',2500000,'DESCRIPTION 39','BRAND 2','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 40','IMAGES_PATH 40',450000,'DESCRIPTION 40','BRAND 2','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 41','IMAGES_PATH 41',760000,'DESCRIPTION 41','BRAND 2','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 42','IMAGES_PATH 42',100000,'DESCRIPTION 42','BRAND 3','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 43','IMAGES_PATH 43',640000,'DESCRIPTION 43','BRAND 1','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 44','IMAGES_PATH 44',100000,'DESCRIPTION 44','BRAND 4','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 45','IMAGES_PATH 45',177000,'DESCRIPTION 45','BRAND 4','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 46','IMAGES_PATH 46',330000,'DESCRIPTION 46','BRAND 1','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 47','IMAGES_PATH 47',650000,'DESCRIPTION 47','BRAND 1','SPORTS CLOTHES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 48','IMAGES_PATH 48',880000,'DESCRIPTION 48','BRAND 1','SPORTS CLOTHES',100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 49','IMAGES_PATH 49',430000,'DESCRIPTION 49','BRAND 1','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 50','IMAGES_PATH 50',410000,'DESCRIPTION 50','BRAND 4','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 51','IMAGES_PATH 51',570000,'DESCRIPTION 51','BRAND 1','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 52','IMAGES_PATH 52',990000,'DESCRIPTION 52','BRAND 2','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 53','IMAGES_PATH 53',250000,'DESCRIPTION 53','BRAND 1','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 54','IMAGES_PATH 54',100000,'DESCRIPTION 54','BRAND 1','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 55','IMAGES_PATH 55',700000,'DESCRIPTION 55','BRAND 3','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 56','IMAGES_PATH 56',100000,'DESCRIPTION 56','BRAND 1','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 57','IMAGES_PATH 57',150000,'DESCRIPTION 57','BRAND 3','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 58','IMAGES_PATH 58',100000,'DESCRIPTION 58','BRAND 1','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 59','IMAGES_PATH 59',100000,'DESCRIPTION 59','BRAND 2','ACCESSORIES',100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND,CATEGORY,QUANTITY) VALUES ( 'PRODUCT NAME 60','IMAGES_PATH 60',1000000,'DESCRIPTION 60','BRAND 2','ACCESSORIES',100);
-- grant access for SHR_Main
GRANT INSERT, SELECT, UPDATE ON dbo.PRODUCTS TO [SHR_Main]

--CREATE TABLE Cart
CREATE TABLE CART_ITEMS (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
USER_ID INT REFERENCES dbo.USERS(ID) ,
PRODUCT_ID INT REFERENCES dbo.PRODUCTS(ID), 
QUANTITY INT
)
GO
INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (3, 1,2);
INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (3, 2,2);
INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (4, 4,3);
INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (4, 5,2);
INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (5, 2,2);
INSERT INTO CART_ITEMS (USER_ID, PRODUCT_ID, QUANTITY) VALUES (5, 3,5);

--

GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.CART_ITEMS TO [SHR_Main]
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.PRODUCTS TO [SHR_Main]



-- order table
CREATE TABLE ORDERS(
ID INT PRIMARY KEY IDENTITY NOT NULL ,
ORDER_ID INT,
USER_ID INT REFERENCES dbo.USERS(ID),
PRODUCT_ID INT REFERENCES dbo.PRODUCTS(ID), 
QUANTITY INT,
GRAND_TOTAL INT,
NOTE NVARCHAR(200),
SHIPPING_ADDRESS NVARCHAR(200),
DATE_CREATE DATE,
STATUS NVARCHAR(100)
)

GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.ORDERS TO [SHR_Main]
INSERT INTO ORDERS VALUES (0,6,12,2,1500000,'FIRST ORDER','SHIPPING ADDRESS 1','2020-12-27','SHIPPED');
INSERT INTO ORDERS VALUES (1,6,12,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES (1,6,13,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES (1,6,14,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES (2,14,12,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES (2,14,15,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES (3,14,19,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES (3,14,12,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES(4,6,12,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');

INSERT INTO ORDERS VALUES(5,12,33,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');
INSERT INTO ORDERS VALUES(5,12,34,2,1500000,'GIAO VÀO THỨ 2','SHIPPING ADDRESS 1','2020-12-27','PENDING');

-- create table wishList
/*
CREATE TABLE WISH_LIST (
USER_ID INT ,
PRODUCT_ID INT,
QUANTITY INT
)
GO
INSERT INTO WISH_LIST (USER_ID, PRODUCT_ID, QUANTITY) VALUES (1, 1,2);
INSERT INTO WISH_LIST (USER_ID, PRODUCT_ID, QUANTITY) VALUES (3, 2,2);
INSERT INTO WISH_LIST (USER_ID, PRODUCT_ID, QUANTITY) VALUES (4, 4,3);
INSERT INTO WISH_LIST (USER_ID, PRODUCT_ID, QUANTITY) VALUES (4, 5,2); 
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.WISH_LIST TO [SHR_Main]
*/
-- create table reviews
CREATE TABLE REVIEWS (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
USER_ID INT REFERENCES dbo.USERS(ID),
PRODUCT_ID INT REFERENCES dbo.PRODUCTS(ID), 
REVIEW NVARCHAR(MAX),
CREATE_TIME DATE
)
GO
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.REVIEWS TO [SHR_Main]
-- create table OTP
CREATE TABLE OTP (
EMAIL NVARCHAR(100) ,
CODE NVARCHAR(100)
)
GO
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.OTP TO [SHR_Main]
INSERT INTO OTP VALUES('A1@GMAIL.COM','123456');
INSERT INTO OTP VALUES('A2@GMAIL.COM','123654');
INSERT INTO OTP VALUES('C1@GMAIL.COM','122456');
INSERT INTO OTP VALUES('C2@GMAIL.COM','12776');
-- edit
ALTER TABLE PRODUCTS
ADD FIRST_IMAGE NVARCHAR(200)  NULL ;
-- ROLES
CREATE TABLE ROLES (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
ROLE_NAME NVARCHAR(100)
)
GO
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.ROLES TO [SHR_Main]
INSERT INTO ROLES VALUES ('ADMIN');
INSERT INTO ROLES VALUES ('CUSTOMER');

