USE WEB_SHR_V1
GO
CREATE TABLE SHIPPING_METHODS(
ID INT PRIMARY KEY IDENTITY NOT NULL ,
NAME NVARCHAR(100) NOT NULL,
DESCRIPTION NVARCHAR(MAX) NOT NULL,
SHIPPING_COST INT NOT NULL,
EARLIEST_DELIVERY_DAY INT NOT NULL,
LATEST_DELIVERY_DAY INT NOT NULL

)
GO
CREATE TABLE PAYMENT_METHODS(
ID INT PRIMARY KEY IDENTITY NOT NULL ,
NAME NVARCHAR(100) NOT NULL,
DESCRIPTION NVARCHAR(MAX) NOT NULL,

)
GO

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY IDENTITY NOT NULL ,
USER_ID INT REFERENCES dbo.USERS(ID) NOT NULL,
RECIPIENT NVARCHAR(200),
EMAIL NVARCHAR(200),
PHONE NVARCHAR(200),
SHIPPING_ADDRESS NVARCHAR(200),
NOTE NVARCHAR(200),
GRAND_TOTAL BIGINT NOT NULL,
SHIPPING_METHOD_ID INT REFERENCES dbo.SHIPPING_METHODS(ID) NOT NULL,
PAYMENT_METHOD_ID INT REFERENCES dbo.PAYMENT_METHODS(ID) NOT NULL,
EARLIEST_DELIVERY_TIME DATE ,
LATEST_DELIVERY_TIME DATE ,
SUCCESSFUL_DELIVERY_TIME DATE,
STATUS NVARCHAR(100) NOT NULL,
CREATE_AT DATE,
UPDATE_AT DATE

)
GO
CREATE TABLE ORDER_ITEMS (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
PRODUCT_ID INT REFERENCES dbo.PRODUCTS(ID) NOT NULL,
QUANTITY INT NOT NULL,
ORDER_ID INT REFERENCES dbo.ORDERS(ORDER_ID) NOT NULL,
)
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.SHIPPING_METHODS TO [SHR_Main]
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.PAYMENT_METHODS TO [SHR_Main]

GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.ORDERS TO [SHR_Main]
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.ORDER_ITEMS TO [SHR_Main]

-- SOLD PRODUCTS
CREATE TABLE SOLD_PRODUCTS (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
PRODUCT_ID INT REFERENCES dbo.PRODUCTS(ID) NOT NULL,
SALE_NUMBER INT ,
SELL_NUMBER INT
)
GO
GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.SOLD_PRODUCTS TO [SHR_Main]

-- AFTER INSERT NEW ORDERS, INCREASE SOLD 

-- AFTER INSERT NEW ORDER_ITEMS, UPDATE SOLD_PRODUCTS TOO

CREATE TRIGGER TG_INSERT_ORDER_ITEMS ON ORDER_ITEMS AFTER INSERT 
AS 
BEGIN
DECLARE @NEW_PID INT = (SELECT PRODUCT_ID FROM inserted)
DECLARE @INPUT_SELL_NUMBER INT = (SELECT QUANTITY FROM inserted)

IF EXISTS (SELECT * FROM SOLD_PRODUCTS WHERE SOLD_PRODUCTS.PRODUCT_ID = @NEW_PID)
	BEGIN
	DECLARE @CURRENT_SALE_NUMBER INT = (SELECT SALE_NUMBER FROM SOLD_PRODUCTS WHERE PRODUCT_ID = @NEW_PID);
	DECLARE @CURRENT_SELL_NUMBER INT = (SELECT SELL_NUMBER FROM SOLD_PRODUCTS WHERE PRODUCT_ID = @NEW_PID);
	SET @CURRENT_SALE_NUMBER = @CURRENT_SALE_NUMBER + 1;
	SET @CURRENT_SELL_NUMBER = @CURRENT_SELL_NUMBER + @INPUT_SELL_NUMBER;
	UPDATE SOLD_PRODUCTS SET SALE_NUMBER = @CURRENT_SALE_NUMBER, SELL_NUMBER = @CURRENT_SELL_NUMBER WHERE PRODUCT_ID = @NEW_PID;
	END
	ELSE
	BEGIN
	INSERT INTO SOLD_PRODUCTS ( PRODUCT_ID, SALE_NUMBER, SELL_NUMBER ) VALUES( @NEW_PID, 1, @INPUT_SELL_NUMBER);
	END

END
GO

GRANT INSERT, SELECT, UPDATE,DELETE ON dbo.REVIEWS TO [SHR_Main]

