use WEB_SHR_V1
go

-- INSERT DATA TO TABLE (DEMO DATA) 15 PRODUCT
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 1','IMAGES_PATH 1',400000,'DESCRIPTION 1',1,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 2','IMAGES_PATH 2',4500000,'DESCRIPTION 2',1,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 3','IMAGES_PATH 3',31000,'DESCRIPTION 3',4,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 4','IMAGES_PATH 4',250000,'DESCRIPTION 4',3,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 5','IMAGES_PATH 5',390000,'DESCRIPTION 5',2,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 6','IMAGES_PATH 6',520000,'DESCRIPTION 6',4,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 7','IMAGES_PATH 7',199000,'DESCRIPTION 7',2,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 8','IMAGES_PATH 8',70000,'DESCRIPTION 8',2,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 9','IMAGES_PATH 9',650000,'DESCRIPTION 9',2,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 10','IMAGES_PATH 10',100000,'DESCRIPTION 10',2,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 11','IMAGES_PATH 11',100000,'DESCRIPTION 11',4,1,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 12','IMAGES_PATH 12',100000,'DESCRIPTION 12',4,1,100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 13','IMAGES_PATH 13',1000000,'DESCRIPTION 13',3,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 14','IMAGES_PATH 14',700000,'DESCRIPTION 14',4,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 15','IMAGES_PATH 15',70000,'DESCRIPTION 15',1,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 16','IMAGES_PATH 16',90000,'DESCRIPTION 16',1,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 17','IMAGES_PATH 17',330000,'DESCRIPTION 17',1,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 18','IMAGES_PATH 18',550000,'DESCRIPTION 18',1,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 19','IMAGES_PATH 19',100000,'DESCRIPTION 19',2,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 20','IMAGES_PATH 20',100000,'DESCRIPTION 20',1,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 21','IMAGES_PATH 21',100000,'DESCRIPTION 21',3,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 22','IMAGES_PATH 22',750000,'DESCRIPTION 22',2,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 23','IMAGES_PATH 23',410000,'DESCRIPTION 23',1,2,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 24','IMAGES_PATH 24',155000,'DESCRIPTION 24',4,2,100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 25','IMAGES_PATH 25',200000,'DESCRIPTION 25',1,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 26','IMAGES_PATH 26',200000,'DESCRIPTION 26',1,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 27','IMAGES_PATH 27',300000,'DESCRIPTION 27',2,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 28','IMAGES_PATH 28',100000,'DESCRIPTION 28',2,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 29','IMAGES_PATH 29',100000,'DESCRIPTION 29',2,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 30','IMAGES_PATH 30',500000,'DESCRIPTION 30',3,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 31','IMAGES_PATH 31',600000,'DESCRIPTION 31',4,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 32','IMAGES_PATH 32',700000,'DESCRIPTION 32',1,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 33','IMAGES_PATH 33',80000,'DESCRIPTION 33',3,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 34','IMAGES_PATH 34',420000,'DESCRIPTION 34',1,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 35','IMAGES_PATH 35',90000,'DESCRIPTION 35',2,3,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 36','IMAGES_PATH 36',150000,'DESCRIPTION 36',1,3,100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 37','IMAGES_PATH 37',100000,'DESCRIPTION 37',1,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 38','IMAGES_PATH 38',800000,'DESCRIPTION 38',4,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 39','IMAGES_PATH 39',2500000,'DESCRIPTION 39',2,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 40','IMAGES_PATH 40',450000,'DESCRIPTION 40',2,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 41','IMAGES_PATH 41',760000,'DESCRIPTION 41',2,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 42','IMAGES_PATH 42',100000,'DESCRIPTION 42',3,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 43','IMAGES_PATH 43',640000,'DESCRIPTION 43',1,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 44','IMAGES_PATH 44',100000,'DESCRIPTION 44',4,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 45','IMAGES_PATH 45',177000,'DESCRIPTION 45',4,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 46','IMAGES_PATH 46',330000,'DESCRIPTION 46',1,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 47','IMAGES_PATH 47',650000,'DESCRIPTION 47',1,4,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 48','IMAGES_PATH 48',880000,'DESCRIPTION 48',1,4,100);

INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 49','IMAGES_PATH 49',430000,'DESCRIPTION 49',1,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 50','IMAGES_PATH 50',410000,'DESCRIPTION 50',4,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 51','IMAGES_PATH 51',570000,'DESCRIPTION 51',1,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 52','IMAGES_PATH 52',990000,'DESCRIPTION 52',2,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 53','IMAGES_PATH 53',250000,'DESCRIPTION 53',1,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 54','IMAGES_PATH 54',100000,'DESCRIPTION 54',1,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 55','IMAGES_PATH 55',700000,'DESCRIPTION 55',3,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 56','IMAGES_PATH 56',100000,'DESCRIPTION 56',1,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 57','IMAGES_PATH 57',150000,'DESCRIPTION 57',3,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 58','IMAGES_PATH 58',100000,'DESCRIPTION 58',1,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 59','IMAGES_PATH 59',100000,'DESCRIPTION 59',2,5,100);
INSERT INTO PRODUCTS (NAME,IMAGES_PATH,PRICE,DESCRIPTION,BRAND_ID,CATEGORY_ID,QUANTITY) VALUES ( 'PRODUCT NAME 60','IMAGES_PATH 60',1000000,'DESCRIPTION 60',2,5,100);