SELECT PRODUCTS.BRAND , COUNT (PRODUCTS.BRAND) FROM PRODUCTS GROUP BY PRODUCTS.BRAND;
SELECT  ORDER_ITEMS.PRODUCT_ID,  SUM(Order_Items.QUANTITY) AS SELLED fROM ORDER_ITEMS GROUP BY ORDER_ITEMS.PRODUCT_ID order by SUM(Order_Items.QUANTITY) desc

select PRODUCTS.* from PRODUCTS, (SELECT  ORDER_ITEMS.PRODUCT_ID,  SUM(Order_Items.QUANTITY) AS SELLED fROM ORDER_ITEMS GROUP BY ORDER_ITEMS.PRODUCT_ID order by SUM(Order_Items.QUANTITY) desc)
 where PRODUCTS.BRAND = 'BRAND 1' 
 SELECT PRODUCTS.* FROM PRODUCTS, (SELECT ORDER_ITEMS.PRODUCT_ID, SUM(Order_Items.QUANTITY) AS SUM_QT FROM ORDER_ITEMS, PRODUCTS WHERE PRODUCTS.ID = ORDER_ITEMS.PRODUCT_ID GROUP BY ORDER_ITEMS.PRODUCT_ID)AS PRODUCT_QT WHERE PRODUCTS.ID = PRODUCT_QT.PRODUCT_ID AND PRODUCTS.BRAND = 'BRAND 1' ORDER BY PRODUCT_QT.SUM_QT DESC
 SELECT * FROM PRODUCTS WHERE BRAND ='BRAND 2';

DECLARE @cnt INT = 1;

WHILE @cnt <=60
BEGIN
  update PRODUCTS set DESCRIPTION = (N'<div class=''col''><h3> Đây là demo về mô tả sản phẩm</h3><p>CHI TIẾT SẢN PHẨM

- Áo Ba lỗ WAN kiểu dáng Slim fit ôm gọn gàng.

- Thiết kế slimfit giúp tôn thêm đường nét nam tính, khoẻ khoắn.

CHẤT LIỆU:

- Chất liệu Cotton tự nhiên mềm mịn, mang đến bề mặt dễ chịu, mượt và nhẹ.

- Áo có khả năng thấm hút mồ hôi tốt, thoát ẩm và thoáng khí.

- Có độ co giãn nhẹ nhờ 5% sợi Spandex.

MÀU SẮC: Trắng , Đen , Xám

SIZE: M – L – XL </p>
<img src="https://salt.tikicdn.com/ts/tmp/a0/90/05/303f8f7d2961974143e11688a31de371.jpg">
</div>') where PRODUCTS.ID = @cnt
   SET @cnt = @cnt + 1;
END;
GO

DECLARE @pid int =1;
DECLARE @ordinal int =1;
WHILE @pid <=60
BEGIN
set @ordinal =1
WHILE @ordinal <=7
begin
insert into SPECIFICATIONS (PRODUCT_ID, ORDINAL, PARAMETER, DETAIL) values (@pid, @ordinal, N'Thông số '+CAST(@ordinal AS nvarchar(100)), N'Giá Trị '+CAST(@ordinal As nvarchar(100)))
SET @ordinal = @ordinal+1;
   end
   SET @pid = @pid+1;
 end
	  go


	  -- brand AMOUNT
	  SELECT BRANDS.ID, COUNT (PRODUCTS.BRAND_ID) AS AMOUNT FROM PRODUCTS, BRANDS WHERE PRODUCTS.BRAND_ID = BRANDS.ID GROUP BY BRANDS.ID;
	  SELECT b.ID, b.NAME, COUNT (p.BRAND_ID) AS AMOUNT FROM PRODUCTS p, BRANDS b WHERE p.BRAND_ID = b.ID GROUP BY b.ID, b.NAME;
	  SELECT BRANDS.*, COUNT(PRODUCTS.BRAND_ID) AS AMOUNT FROM PRODUCTS, BRANDS WHERE PRODUCTS.BRAND_ID = BRANDS.ID GROUP BY BRANDS.ID;
	  SELECT p.* from Products p where p.CATEGORY_ID = 2
	  SELECT PRODUCTS.* from Products where PRODUCTS.CATEGORY_ID = 2
SELECT PRODUCTS.* 
FROM PRODUCTS, (
	SELECT ORDER_ITEMS.PRODUCT_ID, SUM(Order_Items.QUANTITY) AS SUM_QT 
	FROM ORDER_ITEMS, PRODUCTS 
	WHERE PRODUCTS.ID = ORDER_ITEMS.PRODUCT_ID GROUP BY ORDER_ITEMS.PRODUCT_ID)AS PRODUCT_QT 
WHERE PRODUCTS.ID = PRODUCT_QT.PRODUCT_ID AND PRODUCTS.BRAND = ?1 ORDER BY PRODUCT_QT.SUM_QT DESC
SELECT b.id, b.name, COUNT (p.BRAND_ID) FROM Products p, Brands b WHERE p.BRAND_ID = b.ID GROUP BY b.id, b.name
 SELECT PRODUCTS.* FROM PRODUCTS, (SELECT ORDER_ITEMS.PRODUCT_ID, SUM(Order_Items.QUANTITY) AS SUM_QT FROM ORDER_ITEMS, PRODUCTS WHERE PRODUCTS.ID = ORDER_ITEMS.PRODUCT_ID GROUP BY ORDER_ITEMS.PRODUCT_ID)AS PRODUCT_QT WHERE PRODUCTS.ID = PRODUCT_QT.PRODUCT_ID AND PRODUCTS.BRAND_ID = 1  ORDER BY PRODUCT_QT.SUM_QT DESC

 -- popular
 SELECT  PRODUCTS.*, popular FROM PRODUCTS LEFT JOIN
 (SELECT PRODUCTS.ID, COUNT(ORDER_ITEMS.Product_ID ) AS POPULAR FROM PRODUCTS, ORDER_ITEMS WHERE PRODUCTS.ID = ORDER_ITEMS.PRODUCT_ID GROUP BY PRODUCTS.ID ) AS SELLED 
 ON PRODUCTS.ID = SELLED.ID  where PRODUCTS.CATEGORY_ID = 2 ORDER BY POPULAR DESC

 -- best seller
 SELECT  PRODUCTS.*, Best_Seller FROM PRODUCTS LEFT JOIN
 (SELECT PRODUCTS.ID, COUNT(ORDER_ITEMS.Product_ID ) AS Best_Seller FROM PRODUCTS, ORDER_ITEMS WHERE PRODUCTS.ID = ORDER_ITEMS.PRODUCT_ID GROUP BY PRODUCTS.ID ) AS SELLED 
 ON PRODUCTS.ID = SELLED.ID  where PRODUCTS.CATEGORY_ID = 2 ORDER BY Best_Seller DESC
  -- NEW
  SELECT PRODUCTS.* FROM PRODUCTS ORDER BY PRODUCTS.CREATE_AT DESC
  -- expensive
  SELECT PRODUCTS.* FROM PRODUCTS  WHERE CATEGORY_ID =2 ORDER BY PRODUCTS.PRICE DESC
  SELECT  PRODUCTS.ID, PRODUCTS.NAME , SELLED.POPULAR, SELLED.AMOUNT FROM PRODUCTS LEFT JOIN
            (SELECT PRODUCTS.ID, COUNT(ORDER_ITEMS.Product_ID )  AS POPULAR , SUM(ORDER_ITEMS.QUANTITY ) AS AMOUNT  FROM PRODUCTS, ORDER_ITEMS WHERE PRODUCTS.ID = ORDER_ITEMS.PRODUCT_ID GROUP BY PRODUCTS.ID ) AS SELLED 
             ON PRODUCTS.ID = SELLED.ID  where PRODUCTS.BRAND_ID = 2
			 ORDER BY POPULAR DESC

			SELECT P.ID, COUNT_P FROM  (SELECT P2.ID, COUNT(OI.PRODUCT_ID) AS COUNT_P FROM PRODUCTS P2, ORDER_ITEMS OI WHERE P2.ID = OI.PRODUCT_ID GROUP BY P2.ID) AS SELLED right JOIN PRODUCTS P 
			ON P.ID = SELLED.ID WHERE P.BRAND_ID =2 ORDER BY COUNT_P DESC

			
			SELECT P.ID, COUNT_P FROM PRODUCTS P , (SELECT P2.ID, COUNT(OI.PRODUCT_ID) AS COUNT_P FROM PRODUCTS P2, ORDER_ITEMS OI WHERE P2.ID = OI.PRODUCT_ID GROUP BY P2.ID) AS SELLED
		 WHERE P.BRAND_ID =2 ORDER BY COUNT_P DESC
	
	SELECT P.ID, P.NAME , COUNT(OI.PRODUCT_ID) FROM PRODUCTS P, ORDER_ITEMS OI  WHERE P.ID = OI.PRODUCT_ID OR P.ID < 10 GROUP BY P.ID, P.NAME 
	SELECT  PRODUCTS.* FROM PRODUCTS LEFT JOIN(SELECT  PRODUCTS.* FROM PRODUCTS WHERE PRODUCTS.BRAND_ID = 2) AS BR ON PRODUCTS.ID = BR.ID
	----
	  SELECT  PRODUCTS.ID, PRODUCTS.NAME , SELLED.POPULAR, SELLED.AMOUNT FROM PRODUCTS LEFT JOIN
            (SELECT PRODUCTS.ID, COUNT(ORDER_ITEMS.Product_ID )  AS POPULAR , SUM(ORDER_ITEMS.QUANTITY ) AS AMOUNT  FROM PRODUCTS, ORDER_ITEMS WHERE PRODUCTS.ID = ORDER_ITEMS.PRODUCT_ID GROUP BY PRODUCTS.ID ) AS SELLED 
             ON PRODUCTS.ID = SELLED.ID
			 ORDER BY POPULAR DESC
SELECT PRODUCTS.* , SOLD_PRODUCTS.SALE_NUMBER FROM PRODUCTS LEFT JOIN  SOLD_PRODUCTS ON  PRODUCTS.ID = SOLD_PRODUCTS.PRODUCT_ID ORDER BY SALE_NUMBER DESC

SELECT p.* FROM Products p WHERE p.BRAND_ID = 1 ORDER BY p.price

DECLARE @cnt INT = 49

WHILE @cnt <=60
BEGIN
  update PRODUCTS set NAME = (N'Thắt lưng nam da thật mặt khóa tự động – Dây lưng nam cao cấp thiết kế sang trọng lịch lãm – Phụ kiện nam không thể thiếu – DL03') where PRODUCTS.ID = @cnt
   SET @cnt = @cnt + 1;
END;
GO

-- deffaulr rating
DECLARE @cnt INT = 1;

WHILE @cnt <=60
BEGIN
  update PRODUCTS set Rating = 0 where PRODUCTS.ID = @cnt
   SET @cnt = @cnt + 1;
END;
GO

SELECT * FROM Reviews  WHERE product_ID = 22