CREATE TABLE PRODUCTS (
ID INT PRIMARY KEY IDENTITY NOT NULL ,
NAME NVARCHAR(200),
IMAGES_PATH NVARCHAR(100),
PRICE INT,
DESCRIPTION NVARCHAR(MAX),
BRAND_ID INT REFERENCES dbo.BRANDS(ID),
CATEGORY_ID INT REFERENCES dbo.CATEGORIES(ID),
QUANTITY INT
)
GO
ALTER TABLE PAYMENT_METHODS ADD IMAGE NVARCHAR(200)
ALTER TABLE SHIPPING_METHODS ADD IMAGE NVARCHAR(200)

ALTER TABLE PRODUCTS ADD FIRST_IMAGE NVARCHAR(200)
ALTER TABLE CATEGORIES ADD CLASS_ICON NVARCHAR(200)
ALTER TABLE PRODUCTS ADD CREATE_AT DATE
ALTER TABLE PRODUCTS DROP COLUMN PRODUCTS_CREATE_AT
exec sp_rename 'PRODUCTS.[PRODUCTS.CREATE_AT]', 'CREATE_AT', 'COLUMN';

DECLARE @cnt INT = 1;

WHILE @cnt <=60
BEGIN
  update PRODUCTS set CREATE_AT = ('2021-06-14') where PRODUCTS.ID = @cnt
   SET @cnt = @cnt + 1;
END;
GO

DBCC CHECKIDENT (USERS, RESEED, 6)

CREATE TABLE  PERSISTENT_LOGINS (
USER_NAME VARCHAR(64) NOT NULL,
SERIES VARCHAR(64) NOT NULL,
TOKEN VARCHAR(64) NOT NULL,
LAST_USED TIMESTAMP NOT NULL,
PRIMARY KEY (SERIES));

create table logins_persistent(
	username varchar(50) not null,
	series varchar(64) primary key,
	token varchar(64) not null,
	last_used timestamp not null
);

ALTER TABLE USERS ADD OTP NVARCHAR(6);
ALTER TABLE USERS ADD OTP_LIFE_TIME DATETIME;
ALTER TABLE USERS ADD LOCKED BIT;




